Add unPinMessage Method
zSoulweaver/kient pull request #24
Opened 2024-10-11 00:37 UTC by bananacity

added unpin endpoint to remove whatever message is currently pinned

2024-10-11 00:41 UTC, zSoulweaver commented
Lgtm.

I'm currently away on holiday, when I am back, towards the end of next week, I'll merge it in and release a new ver.

Thanks!

2024-10-11 22:27 UTC, bananacity commented
I also fixed the pinMessage endpoint, it unnecesarily stringified the body causing a 422 error with kick. works with this fix now

2024-10-17 11:44 UTC, zSoulweaver requested changes
Just a few nitpicky things is we could fix those up. Otherwise I've tested everything and it seems to work well. :)

2024-10-17 11:44 UTC, zSoulweaver commented on src/endpoints/chat/chat.endpoint.ts
> +        body: body,
Could we shorthand this to just `body,`.

2024-10-17 11:44 UTC, zSoulweaver commented on src/endpoints/chat/chat.endpoint.ts
> +  public async unPinMessage(channel: string) {
Unpin is one word, could we match that here as well, `unpinMessage`.

2024-10-21 10:51 UTC, merged